### PR TITLE
Update lwc_de.properties

### PR DESCRIPTION
**Pull request by xopez**
Made a proper german translation based latest english translation in the dev branch. Hopefully I made no mistakes. Some germans should also look into it and rechange it.

### CODE REVIEW

**Comment by pop4959** [comment]
I know German somewhat fluently, so I can help here. I think you should make the following changes to your translation, to be able to merge it. We can still discuss it further if you disagree, or have further changes to make.

Many of the following changes are suggestions based on how the official German MineCraft translation looks like, or to be more consistent with the previous versions of the German LWC translation.


Missing or incorrect block changes (note many banners just have an added 's'):

ender_chest=Endertruhe
light_blue_shulker_box=Hellblaue Shulkerkiste
lime_shulker_box=Hellgrüne Shulkerkiste

white_banner=Weißes Banner
orange_banner=Oranges Banner
light_blue_banner=Hellblaues Banner
yellow_banner=Gelbes Banner
lime_banner=Hellgrünes Banner
gray_banner=Graues Banner
light_gray_banner=Hellgraues Banner
cyan_banner=Türkises Banner
purple_banner=Violettes Banner
blue_banner=Blaues Banner
brown_banner=Braunes Banner
green_banner=Grünes Banner
red_banner=Rotes Banner
black_banner=Schwarzes Banner

white_wall_banner=Weißes Wandbanner
orange_wall_banner=Oranges Wandbanner
light_blue_wall_banner=Hellblaues Wandbanner
yellow_wall_banner=Gelbes Wandbanner
lime_wall_banner=Hellgrünes Wandbanner
gray_wall_banner=Graues Wandbanner
light_gray_wall_banner=Hellgraues Wandbanner
cyan_wall_banner=Türkises Wandbanner
purple_wall_banner=Violettes Wandbanner
blue_wall_banner=Blaues Wandbanner
brown_wall_banner=Braunes Wandbanner
green_wall_banner=Grünes Wandbanner
red_wall_banner=Rotes Wandbanner
black_wall_banner=Schwarzes Wandbanner

**Other notes**

Revert any extra formatting changes to the file as they can cause problems. For example: first 3 lines, the boxes throughout the file, extra space in "protection.limits", and random new line at line 462.

Of course, still add yourself to the authors list once you've reverted the first 3 lines. An advertisement to your server is not appropriate, as other translators have not been allowed to do so either.

The 4 lines with "protection.interact.rights.remove" should probably say "entfernt", not "gesetzt"

"help.creation":
Change the line
"%white%%cpublic% %gold%Erstellt eine globale Sicherung \n\"
to
"%white%%cpublic% %gold%Erstellt eine öffentliche Sicherung \n\"
and
"%blue%%cprivate% UserName g:GruppenName AndererName \n\"
to
"%blue%%cprivate% Benutzername g:GruppenName AndererName \n\"

"help.modify":
Change the line
"%blue%Azusätzliche Präfixe für Benutzer/Gruppen: \n\"
to
"%blue%Zusätzliche Präfixe für Benutzer/Gruppen: \n\"

**Extra words**

I really like that you added the translation "Diese %block% ist mit einem magischem Zauber gesichert." I love that message XD

**Comment by xopez** [comment]
So hopefully I found all, here is the change.
Just saw "magical spell" in the english file and it sounded nice :D

**Comment by pop4959** [comment]
OK, looks good. I only see 3 issues left:

Re-add previous authors (see your first commit to see who you removed)

lime_wall_banner=Hellgrünes Wandbanner

Also, sorry I did not explain protection limits space problem well enough
"protection.limits":
Change
"%gray%  Aktuelle Sicherungen: %yellow%%protected%"
to
"%gray% Aktuelle Sicherungen: %yellow%%protected%"
              ^notice this space XD
And re-add
"\n\" where it was previously.

Thanks!

**Comment by pop4959** [comment]
Oh also you forgot to add back the translations you removed (like button, etc)

**Comment by xopez** [comment]
new file new try. 
It's better if more people looking over a file so i am really fine :)
If you find anything else, just say it^^

**Comment by pop4959** [comment]
I'm not afraid to tell you if something is still wrong, don't worry.

Only one more thing to fix:
- Re-add Jobsti and PinguinAman to the updaters list.

**Comment by xopez** [comment]
Sure and done

**Comment by pop4959** [comment]
Thank you for all of your hard work! :+1:

**Pull request merged**
