### PR TITLE
 Add new sign types from 1.14

### PR DESCRIPTION
**Pull request by animeavi**

### CODE REVIEW

**Comment by pop4959** [comment]
Thank you, but I think the signs already work without adding them to the config. Might be better to keep it less verbose! I'm assuming you were just adding them to add them, but if there was some deeper reason, let me know and I'll re-open the PR. :smile:

**Comment by animeavi** [comment]
When I was adding LWC integration to Factions I noticed signs didn't get unprotected when faction territory was unclaimed and that was the cause (as in I was reading the blocks that can be protected at runtime from LWC's config).

**Comment by animeavi** [comment]
Actually nevermind, they get detecred using `LWC.isProtectable`, I accidentally reinvented the wheel when LWC already had such a check.

**Comment by pop4959** [comment]
Sounds good. Thanks for taking the time to explain. Good luck with your factions work!

**Pull request closed without merging**
