### PR TITLE
Short and small improve DE

### PR DESCRIPTION
**Pull request by Sprungente**
Hope it's ok ^^ If i find something or fix a mistake from me i wanna pull a new request 💃

### CODE REVIEW

**Comment by pop4959** [comment]
@xopez I just thought I'd bring you into this because these changes look mostly OK to me, but some of it seems like it might be strangely worded. What do you think?

**Comment by Sprungente** [comment]
for line 258-265 
sounds well for changing rights for player and groups. But regions? How does it works with regions? i didn't know about that feature. It is here to give rights to use in this region ? 
What is about lists?

**Comment by pop4959** [comment]
I'm not sure how those work, if they still work. Never used them.

**Comment by xopez** [comment]
I will look at the evening into that. I am now at work and have not much time. But thanks for the mention :)

**Comment by xopez** [comment]
Same here. I never used the regions.
I am fine with the changes.
I think the way with directly speaking to the user and not objectively makes it userfridnlier in my opinion.

**Comment by pop4959** [comment]
Alright after looking at it again I guess it does look fine. Thanks for giving it another look!

**Pull request merged**
